# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Genre.create([{name: 'Metal'},{name: 'Rock'},{name: 'Pop'},{name: 'Grindcore'},
  {name: 'Brutal Death Metal'},{name: 'Bachata'}, {name: 'Reggae'},{name: 'Jazz'}])
Artist.create([{name: 'Martin Peña', bio: 'Biografia', genre_ids: 2},
              {name: 'Claudio Scheihing', bio: 'Estresado por postgres', genre_ids: 7},
              {name: 'Marco Sfogli', bio: 'Guitarrista italiano', genre_ids: 2},
              {name: 'Jason Becker', bio: 'Guitarrista virtuoso con ALS', genre_ids: 2},
              {name: 'Animals as Leaders', bio: 'Grupo instrumental de metal progresivo', genre_ids: 2},
              {name: 'Audioslave', bio: 'Banda de Estados Unidos, RIP Chris Cornell', genre_ids: 2},
              {name: 'Queen', bio: 'Aguante Freddy', genre_ids: 2},
              {name: 'Snarky Puppy', bio: 'Agrupacion de Jazz Fusion', genre_ids: 8},
              {name: 'Toto', bio: 'Banda de Estados Unidos', genre_ids: 2}])
Album.create([{name: 'Perpetual Burn', artist_id: 2, genre_ids: 2},
              {name: 'Weightless', artist_id: 5, genre_ids: 2},
              {name: 'The Madness of Many', artist_id: 5, genre_ids: 2},
              {name: 'The Joy of Motion', artist_id: 5, genre_ids: 2},
              {name: 'Revelations', artist_id: 6, genre_ids: 2},
              {name: 'A Night at the Opera', artist_id: 7, genre_ids: 2},
              {name: 'We like it here', artist_id: 8, genre_ids: 8},
              {name: 'Fahrenheit', artist_id: 9, genre_ids: 2}])
Song.create([{name: 'An Infinite Regression', album_id: 2, artist_id: 5},
  {name: 'Odessa', album_id: 2, artist_id: 5},
  {name: 'Somnarium', album_id: 2, artist_id: 5},
  {name: 'Earth Departure', album_id: 2, artist_id: 5},
  {name: 'Isolated Incidents', album_id: 2, artist_id: 5},
  {name: 'Do Not Go Gently', album_id: 2, artist_id: 5},
  {name: 'New Eden', album_id: 2, artist_id: 5},
  {name: 'Cylindrical Sea', album_id: 2, artist_id: 5},
  {name: 'To Lead You to an Overwhelming Question', album_id: 2, artist_id: 5},
  {name: 'Weightless', album_id: 2, artist_id: 5},
  {name: 'Revelations', album_id: 5, artist_id: 6},
  {name: 'One and the Same', album_id: 5, artist_id: 6},
  {name: 'Sound of a Gun', album_id: 5, artist_id: 6},
  {name: 'Until We Fall', album_id: 5, artist_id: 6},
  {name: 'Original Fire', album_id: 5, artist_id: 6},
  {name: 'Broken City', album_id: 5, artist_id: 6},
  {name: 'Somedays', album_id: 5, artist_id: 6},
  {name: 'Shape of Things to Come', album_id: 5, artist_id: 6},
  {name: 'Jewel of the Summertime', album_id: 5, artist_id: 6},
  {name: 'Wide Awake', album_id: 5, artist_id: 6},
  {name: 'Nothing Left to Say but Goodbye', album_id: 5, artist_id: 6},
  {name: 'Moth', album_id: 5, artist_id: 6},
  {name: 'Death on Two Legs', album_id: 6, artist_id: 7},
  {name: 'Lazing on a Sunday Afternoon', album_id: 6, artist_id: 7},
  {name: 'Im in Love With My Car', album_id: 6, artist_id: 7},
  {name: 'Youre my best friend', album_id: 6, artist_id: 7},
  {name: '39', album_id: 6, artist_id: 7},
  {name: 'Sweet Lady', album_id: 6, artist_id: 7},
  {name: 'Seaside Rendezvous', album_id: 6, artist_id: 7},
  {name: 'The Prophets Song', album_id: 6, artist_id: 7},
  {name: 'Love of My Life', album_id: 6, artist_id: 7},
  {name: 'Good Company', album_id: 6, artist_id: 7},
  {name: 'Bohemian Rhapsody', album_id: 6, artist_id: 7},
  {name: 'God Save the Queen', album_id: 6, artist_id: 7},
  {name: 'Shofukan', album_id: 7, artist_id: 8},
  {name: 'What About Me', album_id: 7, artist_id: 8},
  {name: 'Sleeper', album_id: 7, artist_id: 8},
  {name: 'Jambone', album_id: 7, artist_id: 8},
  {name: 'Kite', album_id: 7, artist_id: 8},
  {name: 'Outlier', album_id: 7, artist_id: 8},
  {name: 'Tio Macaco', album_id: 7, artist_id: 8},
  {name: 'Lingus', album_id: 7, artist_id: 8},
  {name: 'Till the End', album_id: 8, artist_id: 9},
  {name: 'We Can Make It Tonight', album_id:8, artist_id: 9},
  {name: 'Without Your Love', album_id: 8, artist_id: 9},
  {name: 'Cant Stand It Any Longer', album_id: 8, artist_id: 9},
  {name: 'Ill Be Over You', album_id: 8, artist_id: 9},
  {name: 'Fahrenheit', album_id: 8, artist_id: 9},
  {name: 'Somewhere Tonight', album_id: 8, artist_id: 9},
  {name: 'Could This Be Love', album_id: 8, artist_id: 9},
  {name: 'Lea', album_id: 8, artist_id: 9},
  {name: 'Dont Stop Me Now', album_id: 8, artist_id: 9}
  ])
